CREATE TABLE `config_meta` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `app_id` varchar(64) NOT NULL COMMENT '应用ID',
  `code` varchar(64) NOT NULL COMMENT '编码',
  `property` varchar(64) NOT NULL COMMENT '接口属性',
  `column_name` varchar(64) NOT NULL COMMENT '列名',
  `description` varchar(128) NOT NULL DEFAULT '' COMMENT '说明',
  `sort` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT '排序',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`)
) COMMENT='配置元信息表';

CREATE TABLE `config_item` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `app_id` varchar(64) NOT NULL COMMENT '应用ID',
  `meta_code` varchar(64) NOT NULL COMMENT '配置元信息编码',
  `code` varchar(128) NOT NULL DEFAULT '' COMMENT '配置项编码',
  `parent_code` varchar(128) NOT NULL DEFAULT '' COMMENT '父配置项编码',
  `sort` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT '排序',
  `varchar1` varchar(512) NOT NULL DEFAULT '' COMMENT '字符串1',
  `varchar2` varchar(512) NOT NULL DEFAULT '' COMMENT '字符串2',
  `varchar3` varchar(512) NOT NULL DEFAULT '' COMMENT '字符串3',
  `varchar4` varchar(512) NOT NULL DEFAULT '' COMMENT '字符串4',
  `varchar5` varchar(512) NOT NULL DEFAULT '' COMMENT '字符串5',
  `varchar6` varchar(512) NOT NULL DEFAULT '' COMMENT '字符串6',
  `varchar7` varchar(512) NOT NULL DEFAULT '' COMMENT '字符串7',
  `varchar8` varchar(512) NOT NULL DEFAULT '' COMMENT '字符串8',
  `varchar9` varchar(512) NOT NULL DEFAULT '' COMMENT '字符串9',
  `varchar10` varchar(512) NOT NULL DEFAULT '' COMMENT '字符串10',
  `text1` longtext COMMENT '长文本1',
  `text2` longtext COMMENT '长文本2',
  `text3` longtext COMMENT '长文本3',
  `decimal1` decimal(19,4) NOT NULL DEFAULT '0.0000' COMMENT '数字1',
  `decimal2` decimal(19,4) NOT NULL DEFAULT '0.0000' COMMENT '数字2',
  `decimal3` decimal(19,4) NOT NULL DEFAULT '0.0000' COMMENT '数字3',
  `decimal4` decimal(19,4) NOT NULL DEFAULT '0.0000' COMMENT '数字4',
  `decimal5` decimal(19,4) NOT NULL DEFAULT '0.0000' COMMENT '数字5',
  `datetime1` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '日期1',
  `datetime2` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '日期2',
  `datetime3` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '日期3',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`)
) COMMENT='配置条目表';
